### ISSUE TITLE
readme outdated?

### ISSUE THREAD

**Issue by clod44** [auth-xyz/sshman#1]
i'm trying on windows. the repo folder doesn't have a file called `sshman.py`. also i think a `requirements.txt` is expected

**Comment by auth-xyz** [comment]
As the readme states, I have not yet tested the package on windows, however the lack of a sshman.py is infact an issue, though I will be renaming main.py to sshman.py and adding a #! so  it can be executed swfitly. A requirements.txt will also be added.
